# Anzhiyu Config

# Favicon

favicon:
small: https://cdn.luogu.com.cn/upload/usericon/1366636.png
medium: https://cdn.luogu.com.cn/upload/usericon/1366636.png


# Anzhiyu Menu

menu:
  æ–‡ç« :
    åˆ†ç±»: /categories/ || anzhiyu-icon-shapes
    æ ‡ç­¾: /tags/ || anzhiyu-icon-tags

  äº’åŠ¨:
    ç•™è¨€æ¿: /comments/ || anzhiyu-icon-envelope
    Email: mailto:johnchiao@outlook.com || anzhiyu-icon-email

  å…³äºŽ:
    å…³äºŽæœ¬äºº: https://luogu.com.cn/user/1366636 || anzhiyu-icon-paper-plane
    éšä¾¿é€›é€›: javascript:toRandomPost() || anzhiyu-icon-shoe-prints1


# Nav Bar

nav:
  enable: true
  travelling: false
  clock: false
  menu:
    - title: ç½‘é¡µ
      item:
        - name: åšå®¢
          link: https://johnch.pages.dev/
          icon: /img/favicon.png

# ä½œè€…å¡ç‰‡ çŠ¶æ€
author_status:
  enable: true
  skills:
    - ðŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
    - ðŸ” åˆ†äº«ä¸Žçƒ­å¿ƒå¸®åŠ©
    - ðŸƒ è„šè¸å®žåœ°è¡ŒåŠ¨æ´¾

# Social Icons

social:
  Github: https://github.com/JohnChiao75 || anzhiyu-icon-github


# Content Settings

highlight_shrink: true #ä»£ç æ¡†ä¸å±•å¼€ï¼Œéœ€ç‚¹å‡» '>' æ‰“å¼€

# Disable Donating

reward:
  enable: false
